var path = require("path");
var v = process.versions.node.split(".");
if (v[0] <= 10) root += "10_15/";
else if (v[0] <= 11) root += "11_15/";
var d = "";
if (process.platform == "win32" && process.arch == "ia32") d = "win32";
else if (process.platform == "win32" && process.arch == "x64") d = "win64";
else if (process.platform == "darwin" && process.arch == "x64") d = "macos64";
else if (process.platform == "darwin" && process.arch == "arm64") d = "macosa64";
else if (process.platform == "linux" && process.arch == "x64") d = "linux64";
else if (process.platform == "linux" && process.arch == "arm") d = "linuxa7";
else throw process.arch + " on " + process.platform + " is not yet supported";
module_path = path.join(__dirname, "bin", d, "jazz.node");
module.exports = require(module_path);
module.exports.package = require(__dirname + "/package.json");
